spring:
  profiles.active: dev
---
spring:
  profiles: dev
server.port: 1100
application:
  decryptionKey:
datasource:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: DB_DEV_URL
  username: DB_DEV_USERNAME
  password: 4N1ZhjC5JxIvs3X8ulCegpscj/HPY3GA
graphite:
  graphiteReportingEnabled: false
  consoleReportingEnabled: false
  reportRate: 10
  prefix: com.cisco.dft.seed.api
  host: cdtelemetry-sb
  port: 2003
mongodb:
  host: dft-mongo-sb-1
  port: 18000
  database: ci-metrics
  username: dftdevuser
  password: EHYNO3uaX/SSC4Hvqwz7IsSaoxPoOeTE
  authenticationDB: ci-metrics
---
spring:
  profiles: stage
server.port: 1100
application:
  decryptionKey:
datasource:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: DB_STAGE_URL
  username: DB_STAGE_USERNAME
  password: 5OyRkLiWOtWnIM8gwwof04s6TTJ44tG0PwuBYkyNfEo=
graphite:
  graphiteReportingenabled: false
  consoleReportingEnabled: false
  reportRate:
  prefix: 
  host:
  port:
mongodb:
  host: DB_STG_URL
  port: 27017
  database: sampleUserDB
  username: scott
  password: C0uJpXMXn/HV+1+d5LZdEQ==
  authenticationDB: sampleAdminDB
---
spring:
  profiles: prod
server.port: 1100
application:
  decryptionKey:
datasource:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: DB_PROD_URL
  username: DB_PROD_USERNAME
  password: 8E7ou21wxJfQSEPjccXumIwunn11RSc8MFKkr1dShUM=
graphite:
  graphiteReportingenabled: false
  consoleReportingEnabled: false
  reportRate:
  prefix: 
  host:
  port:
mongodb:
  host: DB_PROD_URL
  port: 27017
  database: sampleUserDB
  username: scott
  password: wiXq/dhaMd370kXBjW9qdQ==
  authenticationDB: sampleAdminDB